const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const code=fs.readFileSync(path.join(__dirname,'../HelperScripts/UTILITY_SourceProjects.jsx'),'utf8');let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
function setup(){
 const files={},closed=[],alerts=[],events=[];
 function File(p){this.fsName=p;this.name=p.split('/').pop();}
 Object.defineProperties(File.prototype,{exists:{get(){return this.fsName in files;}},length:{get(){return String(files[this.fsName]||'').length;}}});
 File.prototype.open=function(){return this.exists;};File.prototype.read=function(){return files[this.fsName];};File.prototype.close=function(){closed.push(this.fsName);};
 class FootageItem{constructor(name,file,still=true){this.name=name;this.file=file;this.mainSource={isStill:still};}}
 class CompItem{constructor(name){this.name=name;}}
 class FolderItem{constructor(name,items=[]){this.name=name;this.items=items;}get numItems(){return this.items.length;}item(i){return this.items[i-1];}}
 function XMPFile(p){this.getXMP=()=>{if(files[p] instanceof Error)throw files[p];return files[p];};this.closeFile=()=>closed.push(p);}
 const c={File,FootageItem,CompItem,FolderItem,XMPFile,XMPMeta:function(p){if(p==='bad')throw Error('corrupt');return meta(p);},XMPConst:{NS_CREATOR_ATOM:'creator',NS_DM:'dm'},$:{os:'Macintosh'},alert:s=>alerts.push(s),ImportOptions:function(file){this.file=file;},getFolderByName:name=>new FolderItem(name),app:{beginUndoGroup:()=>events.push('begin'),endUndoGroup:()=>events.push('end'),project:{selection:[],importFile:()=>{throw Error('unconfigured');}}}};
 vm.createContext(c);vm.runInContext(code,c);return {c,files,closed,alerts,events,File,FootageItem,CompItem,FolderItem};
}
function meta(p,kind='creator'){return {getStructField(ns,struct,fieldNs,field){if(kind==='creator'&&ns==='creator'&&struct==='aeProjectLink'&&field==='fullPath'||kind==='dm'&&ns==='dm'&&struct==='projectRef'&&field==='path')return {value:p};},getProperty(){}};}
test('Reads canonical creatorAtom and Dynamic Media project paths',()=>{const {c}=setup();assert.equal(c.toolboxSourcePaths(meta('/job/a.aep'))[0],'/job/a.aep');assert.equal(c.toolboxSourcePaths(meta('/job/a.aepx','dm'))[0],'/job/a.aepx');assert.equal(c.toolboxSourcePaths(meta('/job/not-a-project.psd')).length,0);});
test('Still images and sequences are scanned and shared source projects deduplicated',()=>{const {c,files,File,FootageItem}=setup();files['/a.png']=meta('/job/a.aep');files['/b0001.tif']=meta('/job/a.aep');files['/job/a.aep']='project';const result=c.toolboxSourceDiscover([new FootageItem('a.png',new File('/a.png')),new FootageItem('sequence',new File('/b0001.tif'),false)],'','');assert.equal(result.records.length,1);});
test('Reads either exact sidecar convention even when embedded metadata fails',()=>{for(const name of ['/a.png.xmp','/a.xmp']){const {c,files,closed,File}=setup();files['/a.png']=Error('unsupported');files[name]='/job/a.aep';const result=c.toolboxSourceRead(new File('/a.png'));assert.equal(result.paths[0],'/job/a.aep');assert(closed.includes('/a.png'));assert(closed.includes(name));}});
test('Corrupt sidecar and missing metadata produce per-file notices without crashing',()=>{const {c,files,File,FootageItem,closed}=setup();files['/a.png']=null;files['/a.xmp']='bad';const result=c.toolboxSourceDiscover([new FootageItem('a',new File('/a.png'))],'','');assert.equal(result.records.length,0);assert(result.notices[0].includes('no AE project link'));assert(closed.includes('/a.xmp'));});
test('Offline media and non-file selections are skipped',()=>{const {c,File,FootageItem,CompItem}=setup();const r=c.toolboxSourceDiscover([new FootageItem('offline',new File('/missing.png')),new CompItem('comp')],'','');assert.equal(r.notices.length,2);assert.equal(r.records.length,0);});
test('Resolves file URI, Windows and UNC paths with configured root mapping',()=>{const {c,files}=setup();assert.equal(c.toolboxSourceNormalize('file:///C:/job/a%20b.aep'),'C:/job/a b.aep');assert.equal(c.toolboxSourceNormalize('file://server/share/a.aep'),'//server/share/a.aep');files['/Volumes/jobs/a.aep']='';assert.equal(c.toolboxSourceResolve('Z:\\jobs\\a.aep','Z:/jobs','/Volumes/jobs').fsName,'/Volumes/jobs/a.aep');assert.equal(c.toolboxSourceResolve('Z:/jobsExtra/a.aep','Z:/jobs','/Volumes/jobs').fsName,'Z:/jobsExtra/a.aep');});
test('Missing project path stays visible and invalid relative path is rejected',()=>{const {c}=setup();assert.equal(c.toolboxSourceResolve('/moved/a.aep','','').exists,false);assert.equal(c.toolboxSourceResolve('a.aep','',''),null);assert.equal(c.toolboxSourceResolve('https://host/a.aep','',''),null);});
test('Only newly imported matching compositions are moved',()=>{const {c,files,File,CompItem,FolderItem,events}=setup();files['/a.aep']='';const existing=new CompItem('render'),newComp=new CompItem('render'),other=new CompItem('other');const imported=new FolderItem('a',[newComp,other]);c.app.project.importFile=()=>imported;c.app.project.existing=existing;c.toolboxSourceImport([{file:new File('/a.aep')}],[{name:'render.png'}]);assert.equal(newComp.parentFolder.name,'ImportedComps');assert.equal(existing.parentFolder,undefined);assert.equal(other.parentFolder,undefined);assert.deepEqual(events,['begin','end']);});
test('A failed project import closes undo and reports the failure',()=>{const {c,files,File,events,alerts}=setup();files['/a.aep']='';c.toolboxSourceImport([{file:new File('/a.aep')}],[]);assert.deepEqual(events,['begin','end']);assert(alerts[0].includes('unconfigured'));});
test('Empty selection gives an instruction before opening any dialog',()=>{const {c,alerts}=setup();c.toolboxSourceDialog('','');assert(alerts[0].includes('Select rendered'));});
console.log(passed+' source project tests passed.');
